# Generated by Django 2.2.1 on 2019-06-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('OFF', 'Job offered'), ('APP', 'Applied to job'), ('REJ', 'Application rejected')], default='APP', max_length=3),
        ),
    ]
