# Generated by Django 2.2.1 on 2019-06-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_applied',
            field=models.DateTimeField(),
        ),
    ]
