# Generated by Django 2.2.1 on 2019-07-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190630_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_applied',
        ),
    ]
